---
sidebar: sidebar 
permalink: rn/about.html 
keywords:  
summary:  
---
= Informationen zu diesem Release
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Dokumentation auf dieser Website beschreibt die Astra Control REST API und damit verbundene Automatisierungstechnologien, die mit der April 2022 (22.04) Version von Astra Control verfügbar sind. Diese Version der REST-API ist insbesondere mit den entsprechenden 22.04 Versionen von Astra Control Center und Astra Control Service enthalten.

Weitere Informationen zu diesem Release sowie zu vorherigen Versionen finden Sie auf den folgenden Seiten und den folgenden Websites:

* link:../rn/whats_new.html["Neuerungen bei der Astra Control REST-API"]
* link:../endpoints/resources.html["REST-Ressourcen und -Endpunkte"]
* https://docs.netapp.com/us-en/astra-control-center-2204/["Astra Control Center 22.04-Dokumentation"^]
* https://docs.netapp.com/us-en/astra-control-service/["Dokumentation des Astra Control Service"^]
* link:../aa-earlier-versions.html["Frühere Versionen der Dokumentation von Astra Automation"]

